$(call configure-package,\
	https://netfilter.org/projects/libnftnl/files/libnftnl-1.2.5.tar.xz,\
	966de0a8120c8a53db859889749368bfb2cba0c4f0b4c1a30d264eccc45f1226,\
	LIBMNL_CFLAGS='-I$${libmnl}/include' LIBMNL_LIBS='-L$${libmnl}/src/.libs -lmnl'\
)
