$(call configure-package,\
	https://www.netfilter.org/projects/iptables/files/iptables-1.8.9.tar.xz,\
	ef6639a43be8325a4f8ea68123ffac236cb696e8c78501b64e8106afb008c87f,\
	--enable-static --disable-shared --disable-ipv6 --disable-largefile --disable-devel --disable-nftables --disable-connlabel\
)
